// This would typically connect to a real AI service
// For now, we'll use a simple simulation

// Preset responses for common questions
const responses: Record<string, string> = {
  'carbon footprint': 'Your carbon footprint is the total amount of greenhouse gases (including carbon dioxide and methane) that are generated by your actions. The main sources include transportation, home energy use, food choices, and consumption habits.',
  'reduce emissions': 'To reduce your carbon emissions, consider: using public transportation, walking or biking, improving home energy efficiency, reducing meat consumption, and minimizing waste. Small changes can add up to significant reductions!',
  'carbon offset': 'Carbon offsets are a way to compensate for your emissions by funding projects that reduce greenhouse gas emissions elsewhere. These might include renewable energy, forest conservation, or methane capture projects.',
  'composting': 'Composting is the natural process of recycling organic matter into a valuable fertilizer. You can compost fruit and vegetable scraps, coffee grounds, yard trimmings, and more. It reduces methane emissions from landfills and creates nutrient-rich soil.',
  'recycling': 'Recycling helps reduce waste, conserve resources, and decrease pollution. Be sure to clean containers before recycling, follow your local guidelines, and remember that not all plastics are recyclable.',
  'hello': 'Hello! I\'m Djen, your AI assistant for carbon footprint and waste management. How can I help you today?',
  'hi': 'Hi there! I\'m Djen. I can help you understand and manage your environmental impact. What would you like to know about?'
};

// Check input against keywords to find the best matching response
export const generateResponse = async (input: string): Promise<string> => {
  // Simulate network delay
  await new Promise(resolve => setTimeout(resolve, 1500));
  
  const lowercaseInput = input.toLowerCase();
  
  // Check for exact matches first
  if (responses[lowercaseInput]) {
    return responses[lowercaseInput];
  }
  
  // Check for partial matches
  for (const [key, response] of Object.entries(responses)) {
    if (lowercaseInput.includes(key)) {
      return response;
    }
  }
  
  // Default response if no matches
  return "I'm here to help with questions about carbon footprints, waste management, and sustainability. Could you please provide more details about what you'd like to know?";
};
